spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

---
spring:
  config:
    activate:
      on-profile: default
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: dummy:9092
  jpa:
    open-in-view: false
