spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

---

spring:
  config:
    activate:
      on-profile: default
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka.prod.myserver.com:9092}
  jpa:
    open-in-view: false
